apiVersion: v1
kind: LimitRange
metadata:
  name: example-limitrange
  namespace: distributed-db
spec:
  limits:
  - max:
      cpu: "800m"
      memory: "1Gi"
    min:
      cpu: "100m"
      memory: "100Mi"
    type: Pod

  - max:
      cpu: "400m"
      memory: "500Mi"
    min:
      cpu: "100m"
      memory: "100Mi"
    default:
      cpu: "200m"
      memory: "250Mi"
    defaultRequest:
      cpu: "150m"
      memory: "150Mi"
    type: Container
