apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: db-clean-vpa
  namespace: distributed-db
spec:
  targetRef:
    apiVersion: "apps/v1"
    kind:       Deployment
    name:       db-clean-deployment
  updatePolicy:
    updateMode: "Auto"
  resourcePolicy:
    containerPolicies:
      - containerName: consumer
        minAllowed:
          cpu: "50m"      # Minimum resources the VPA can scale down to.
          memory: "100Mi"
        maxAllowed:
          cpu: "500m"     # Maximum resources the VPA can scale up to.
          memory: "1Gi"
        controlledResources: ["cpu", "memory"]
