apiVersion: apps/v1
kind: Deployment
metadata:
  name: vector-reduce-deployment
  namespace: vector-reduce
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vector-reduce
  template:
    metadata:
      labels:
        app: vector-reduce
    spec:
      containers:
      - name: vector-reduce
        image: mateobur/vector-reduce:0.1
        resources:
          limits:
            cpu: "2"
          requests:
            cpu: "0.2"

